export const costosDelivery = [
  { departamento: 'LIMA', provincia: 'LIMA', distrito: 'COMAS', valor: 12 },
  {
    departamento: 'LIMA',
    provincia: 'LIMA',
    distrito: 'EL AGUSTINO',
    valor: 12,
  },
  {
    departamento: 'LIMA',
    provincia: 'LIMA',
    distrito: 'INDEPENDENCIA',
    valor: 12,
  },
  {
    departamento: 'LIMA',
    provincia: 'LIMA',
    distrito: 'JESUS MARIA',
    valor: 12,
  },
  { departamento: 'LIMA', provincia: 'LIMA', distrito: 'LA MOLINA', valor: 16 },
  {
    departamento: 'LIMA',
    provincia: 'LIMA',
    distrito: 'LA VICTORIA',
    valor: 12,
  },
  { departamento: 'LIMA', provincia: 'LIMA', distrito: 'LIMA', valor: 12 },
  { departamento: 'LIMA', provincia: 'LIMA', distrito: 'LINCE', valor: 12 },
  {
    departamento: 'LIMA',
    provincia: 'LIMA',
    distrito: 'LOS OLIVOS',
    valor: 12,
  },
  {
    departamento: 'LIMA',
    provincia: 'LIMA',
    distrito: 'MAGDALENA DEL MAR',
    valor: 12,
  },
  {
    departamento: 'LIMA',
    provincia: 'LIMA',
    distrito: 'MIRAFLORES',
    valor: 12,
  },

  {
    departamento: 'LIMA',
    provincia: 'LIMA',
    distrito: 'PUEBLO LIBRE',
    valor: 12,
  },
  {
    departamento: 'LIMA',
    provincia: 'LIMA',
    distrito: 'PUENTE PIEDRA',
    valor: 16,
  },
  { departamento: 'LIMA', provincia: 'LIMA', distrito: 'RIMAC', valor: 12 },
  { departamento: 'LIMA', provincia: 'LIMA', distrito: 'SAN BORJA', valor: 12 },
  {
    departamento: 'LIMA',
    provincia: 'LIMA',
    distrito: 'SAN ISIDRO',
    valor: 12,
  },
  {
    departamento: 'LIMA',
    provincia: 'LIMA',
    distrito: 'SAN JUAN DE LURIGANCHO',
    valor: 16,
  },
  {
    departamento: 'LIMA',
    provincia: 'LIMA',
    distrito: 'SAN JUAN DE MIRAFLORES',
    valor: 16,
  },
  { departamento: 'LIMA', provincia: 'LIMA', distrito: 'SAN LUIS', valor: 12 },
  {
    departamento: 'LIMA',
    provincia: 'LIMA',
    distrito: 'SAN MARTIN DE PORRES',
    valor: 12,
  },
  {
    departamento: 'LIMA',
    provincia: 'LIMA',
    distrito: 'SAN MIGUEL',
    valor: 12,
  },
  {
    departamento: 'LIMA',
    provincia: 'LIMA',
    distrito: 'SANTA ANITA',
    valor: 12,
  },

  {
    departamento: 'LIMA',
    provincia: 'LIMA',
    distrito: 'SANTIAGO DE SURCO',
    valor: 12,
  },
  { departamento: 'LIMA', provincia: 'LIMA', distrito: 'SURQUILLO', valor: 12 },
  {
    departamento: 'LIMA',
    provincia: 'LIMA',
    distrito: 'VILLA EL SALVADOR',
    valor: 16,
  },
  {
    departamento: 'LIMA',
    provincia: 'LIMA',
    distrito: 'VILLA MARIA DEL TRIUNFO',
    valor: 16,
  },
  { departamento: 'LIMA', provincia: 'LIMA', distrito: 'ATE', valor: 18 },
  { departamento: 'LIMA', provincia: 'LIMA', distrito: 'BARRANCO', valor: 12 },
  { departamento: 'LIMA', provincia: 'LIMA', distrito: 'BREÑA', valor: 12 },
  {
    departamento: 'LIMA',
    provincia: 'LIMA',
    distrito: 'CARABAYLLO',
    valor: 16,
  },

  {
    departamento: 'LIMA',
    provincia: 'LIMA',
    distrito: 'CHORRILLOS',
    valor: 12,
  },
  {
    departamento: 'CALLAO',
    provincia: 'CALLAO',
    distrito: 'BELLAVISTA',
    valor: 12,
  },
  {
    departamento: 'CALLAO',
    provincia: 'CALLAO',
    distrito: 'CALLAO',
    valor: 12,
  },
  {
    departamento: 'CALLAO',
    provincia: 'CALLAO',
    distrito: 'CARMEN DE LA LEGUA REYNOSO',
    valor: 12,
  },
  {
    departamento: 'CALLAO',
    provincia: 'CALLAO',
    distrito: 'LA PERLA',
    valor: 12,
  },
  {
    departamento: 'CALLAO',
    provincia: 'CALLAO',
    distrito: 'LA PUNTA',
    valor: 12,
  },
  {
    departamento: 'CALLAO',
    provincia: 'CALLAO',
    distrito: 'MI PERU',
    valor: 12,
  },
  {
    departamento: 'CALLAO',
    provincia: 'CALLAO',
    distrito: 'VENTANILLA',
    valor: 12,
  },
];
